[package]
name = "SSHBindpy"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "SSHBindpy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.3"
sshbind = "0.0.1"
